### ISSUE TITLE
Output header

### ISSUE THREAD

**Issue by gbnegrini** [duolinwang/CircRNAFisher#2]
Hi!
I have finished all the pipeline and obtained the file "backsplice_passcutoff.txt", but the header of this file and all other output files is missing. So it is not possible to understand the data of each columns.
These are the first 4 lines of the output file:
```chr6,134137030,134137208	6	6	0	0	0.0018567067218397	0	0.000000e+00	-1.67,0.33,249.81	None
chr6,77959140,78166356	6	4	2	2	0.0018567067218397	0	0.000000e+00	-1.50,0.25,255.00	NM_133614	0	322	160612	77959140	78166356	Slc25a21
chr14,81962620,81989620	5	5	0	0	0.000899544540321412	0	0.000000e+00	0.00,0.00,255.00	None
chr1,77297599,77299539	6	6	0	0	0.00373789135317139	0	0.000000e+00	-5.33,1.17,100.01	None
chr6,132662296,134148498	23	23	0	0	0.0018567067218397	0	0.000000e+00	-11.13,2.17,255.00	NM_001013170	0	2874	25260	132662296,132773885,132777016,132777395,132778942,132783500,132784056,132788763,132790732,132797505,132802155	132772518,132774026,132777190,132777508,132779043,132783683,132784176,132788872,132790946,132797678,134148498	Wars
```

**Comment by duolinwang** [comment]
Sorry for the misleading. In this version, we didn't put the header in the output file, I added the explanation in the readme file. Hope it can make you understand the output file batter. Actually, the name of the output file is "backsplice_passcutoff.txt" as you got.

**Comment by gbnegrini** [comment]
Thank you for such a fast response, you explanation helped a lot.

**Comment by gbnegrini** [comment]
Thank you for such a fast response, your explanation helped a lot.
